name: ci_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11.9
  - faiss-cpu==1.8.0 
  - numpy==1.26.4
  - pillow==10.3.0
  - pytest==7.4.0
  - pytest-mock==3.10.0
  - pytorch==2.3.0
  - torchvision==0.18.0
  - transformers==4.37.2
  - setuptools==68.2.2
