# Uses latest versions, supported on Ubuntu and MacOS[Arm]
# Does not support MacOS[Intel] or Windows.
name: latest-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - faiss-cpu==1.8.0 
  - numpy==1.26.4
  - pillow==10.3.0
  - pytest==7.4.0
  - pytest-mock==3.10.0
  - pytorch==2.3.0
  - torchvision==0.18.0
  - transformers==4.37.2
