name: ci_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python
  - faiss-cpu
  - numpy
  - pillow
  - pytest
  - pytest-mock
  - pytorch
  - torchvision
  - transformers
  - setuptools
