name: Python Application Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Environment Setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          miniconda-version: "latest"
          environment-file: environments.yml
          activate-environment: ci_env

      - name: Install dependencies
        run: conda env update --file environments.yml --name ci_env

      - name: Run Tests
        run: |
          conda activate ci_env
          pytest test

